### ISSUE TITLE
About language and skyblock support

### ISSUE THREAD

**Issue by Adam1609** [TheKillerTacos/SkyBlock#3]
Can you add language support? And I cant create an island, im using Alpha version!

TheKillerTaco´s Todo:

- [ ] English Support

- [x] Fix Island Code

- [ ] Fix Generator Island Code

**Comment by TheKillerTacos** [comment]
Soon I'll add it. I'm checking the island generator. So rather wait.

**Comment by TheKillerTacos** [comment]
Hi, Maybe try removing the Lobby name "world" as default, change it in the Config.yml, ill soon add the multi language support, and im fixing the error since setblock() aint working, so the island cant be generated.

**Comment by Adam1609** [comment]
Its okay to change the name of the world? I feel worry

**Comment by Adam1609** [comment]
and does it support water or lava or chest?

**Comment by TheKillerTacos** [comment]
Just in the skyblock file config. And I'll add that so it can be received to your inv. Soon I'll add the chest. Since this plugin was old.

**Comment by Adam1609** [comment]
Can you add a vietnamese translate? I want to translate because my staff doesnt know english much.

**Comment by TheKillerTacos** [comment]
ok, but ill work on this plugin on sunday, or saturday night, im working on something else by now..

**Comment by Adam1609** [comment]
I liked this plugin! But waiting is so long for me...

**Comment by TheKillerTacos** [comment]
Haha, sorry for not working on the plugin, but since im banned/tempBanned from PM Forums, ill have to wait, but ill start making the multilanguage support

**Comment by Adam1609** [comment]
I will wait if u done the multilanguage

**Comment by TheKillerTacos** [comment]
Closing issue, Rewriting code from scratch, also creating both Php5 and php7 versions (first PHP5)
